### ISSUE TITLE
Dynamic imaging and better documentation for newcomers to imageflow

### ISSUE THREAD

**Issue by kurtgronbech** [imazen/imageflow-dotnet#1]
I'm coming from ImageResizer and I'm new to imageflow. I'm finding it hard to figure out if imageflow-dotnet can solve the problem of dynamic imaging via Azure Storage in ASP.NET Core, like the ImageResizer/AzureReader2 combination I have previously used. 

In my ASP.NET Core 2 project I need: 

1) /prefix/image.jpg?width=xxxx
2) Read image from Azure Storage, like the AzureReader2 plugin did for ImageResizer
3) Return resized image to the browser

If imageflow-dotnet can solve this problem then how exactly should this be configured in my Core 2 project? 

I have installed ImageFlow.net from Nuget. 

Some easy to discover documentation on how to use it in such scenarios could probably help spread the usage a bit faster.

**Comment by kurtgronbech** [comment]
I have som progress with the help from the unit tests and from [this article on Stackoverflow](https://stackoverflow.com/questions/41421280/serving-images-from-azure-blob-storage-in-dot-net-core). 

But also some exceptions. I'll describe what I have done just in case it may help others get some traction with this exact scenario. 

Using **FluentBuildJob** and **JobContext** I get lots of exceptions even though it seems to work anyway. The exceptions are lots of "PInvokeStackImbalance" like the following: 

_Managed Debugging Assistant 'PInvokeStackImbalance' : 'A call to PInvoke function 'Imageflow.Net!Imageflow.Bindings.NativeMethods::imageflow_context_create' has unbalanced the stack. This is likely because the managed PInvoke signature does not match the unmanaged target signature. Check that the calling convention and parameters of the PInvoke signature match the target unmanaged signature.'_

Any ideas? My system is Windows 10, Intel Core i7 4850HQ, Haswell chipset. 

Imageflow.Net (0.2.6)
Imageflow.NativeRuntime.win-x86 (1.0.0-rc7)

Here's the test code. 

1. I created a BlobFileHandler middleware and mapped it to "/images" path from Startup.cs with

`app.Map(new PathString("/images/upload"), a => a.UseBlobFileHandler());`

2. In Azure Storage my files are stored in "upload" container and the BlobFileHandler downloads the blob from there and use either **FluentBuildJob** or **JobContext** to process the file before sending it to the response stream. Both FluentBuildJob and JobContext works. 

The BlobFileHandler looks like this although CloudStorageAccount etc should be separated out in a service, of course.  And I'm not sure if it is correct usage of the memory streams etc. 

Any input is much appreciated. 

```
public class BlobFileHandler
{
	public BlobFileHandler(RequestDelegate next)
	{
	}

	public async Task Invoke(HttpContext httpContext)
	{
		string connectionString = "<storage connection string>"; 
		string itemPath = httpContext.Request.Path.Value.TrimStart('/');		

		string extension = Path.GetExtension(itemPath); 		

		CloudStorageAccount storageAccount = CloudStorageAccount.Parse(connectionString); 
		CloudBlobClient blobClient = storageAccount.CreateCloudBlobClient();		
		CloudBlobContainer container = blobClient.GetContainerReference("upload");
		CloudBlockBlob cbb = container.GetBlockBlobReference(itemPath);
		
		using (MemoryStream memoryStream = new MemoryStream())
		{
			await cbb.DownloadToStreamAsync(memoryStream);

// Using FluentBuildJob
			BuildJobResult r;
			using (var b = new FluentBuildJob())
			{
							
				r = await b.Decode(memoryStream, false).FlipHorizontal().Rotate90().Distort(30, 20).ConstrainWithin(5, 5)
					.EncodeToBytes(new LibJpegTurboEncoder()).FinishAsync();

				var bytes = r.First.TryGetBytes();

				using (var stream = new MemoryStream(bytes.Value.Array, bytes.Value.Offset, bytes.Value.Count))
				{					
					
					httpContext.Response.ContentType = "image/jpeg";//cbb.Properties.ContentType;        							
					await stream.CopyToAsync(httpContext.Response.Body);
				}
				
			}

// Using JobContext and ImageResizer4 commands:
#if false
			using (var c = new JobContext())
			{				
				c.AddInputBytesPinned(0, memoryStream.GetBuffer());
				c.AddOutputBuffer(1);				
				var response = c.ExecuteImageResizer4CommandString(0, 1, "w=200&h=200&scale=both&format=png");

				var data = response.DeserializeDynamic();				
				var outputStream = c.GetOutputBuffer(1); 						

				//Assert.Equal(200, (int)data.code);
				//Assert.Equal(true, (bool)data.success);		

				httpContext.Response.ContentType = "image/png";//cbb.Properties.ContentType;   
				await outputStream.CopyToAsync(httpContext.Response.Body);				
			}	
#endif			
		}

	}
}

```
```
// Extension method used to add the middleware to the HTTP request pipeline.
public static class BlobFileHandlerExtensions
{
	public static IApplicationBuilder UseBlobFileHandler(this IApplicationBuilder builder)
	{
		return builder.UseMiddleware<BlobFileHandler>();
	}
}

```

**Comment by nathanaeljones** [comment]
Are you on AnyCPU, x86, or x64? Does the unbalanced stack error happen on all of these?

**Comment by kurtgronbech** [comment]
It turns out it only happens on x86. It works without ubalanced stack after switching to x64 with Imageflow.NativeRuntime.win-x86_64-sandybridge (now version rc8... I see that you've updated since yesterday). 

It still happens on x86 with Imageflow.NativeRuntime.win-x86 (1.0.0-rc8).

**Comment by nathanaeljones** [comment]
I have the same MDA on to detect unbalanced stacks o x86, but haven't been able to do so under a Haswell-series CPU and Windows 10. Are there any other details you can think of?

I'll provide a streamlined example when I get some time.

**Comment by Robelind** [comment]
Where can the example be found?

**Comment by lilith** [comment]
I would suggest looking at Imageflow.NET Server, https://github.com/imazen/imageflow-dotnet-server instead of rolling your own middleware. I think we've resolved all concerns mentioned on this thread, please open a new one if we missed something.
