### ISSUE TITLE
DllNotFoundException: Unable to load shared library 'libdl.so' or one of its dependencies

### ISSUE THREAD

**Issue by mcm-ham** [imazen/imageflow-dotnet#10]
I've installed:

Imageflow.NativeRuntime.ubuntu_18_04-x86_64  1.1.0-rc18
Imageflow.Net  1.1.0-rc18

On top of this docker image:
mcr.microsoft.com/dotnet/core/runtime:3.1-bionic

But I see this error at runtime:
> DllNotFoundException: Unable to load shared library 'libdl.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibdl.so: cannot open shared object file: No such file or directory

Do you know what I'm missing? It works fine on Windows.

**Comment by mcm-ham** [comment]
Following this instruction seemed to fix it for me:
https://github.com/dotnet/dotnet-docker/issues/618#issuecomment-405979425

**Comment by lilith** [comment]
Ok, thank you.
