### ISSUE TITLE
Native DLLs not copied to output directory

### ISSUE THREAD

**Issue by andrewdavey** [imazen/imageflow-dotnet#12]
I created a new ASP.NET Core Web Application with the following csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <CopyRefAssembliesToPublishDirectory>false</CopyRefAssembliesToPublishDirectory>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Imageflow.NativeRuntime.win-x86_64" Version="1.3.7-rc37" />
    <PackageReference Include="Imageflow.Net" Version="0.4.4" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="3.1.3" />
  </ItemGroup>

</Project>
```

After building in Visual Studio, the project's `bin\Debug\netcoreapp3.1` directory does not contain the native DLL.

Am I doing something wrong? Should referencing the native package work like I have it?

**Comment by lilith** [comment]
Could you attach a .zip of the new project you created so I can reproduce this faster?

**Comment by lilith** [comment]
Is your build set to AnyCPU or x64?

**Comment by andrewdavey** [comment]
It's an AnyCPU build.

Sorry, after checking more closely I found the native DLL nested within `runtimes\win-x64\native`.

**Comment by lilith** [comment]
Usually you'll need to set the build to x64 to get binaries to copy. Is Imageflow working for you now?

**Comment by lilith** [comment]
I would suggest updating to v0.5 -> https://github.com/imazen/imageflow-dotnet/releases/tag/v0.5.0

Lots of improvements and several bug fixes. This corresponds to Imageflow 1.3.8-rc38 and later.

**Comment by andrewdavey** [comment]
Thank you that's working now.
