### ISSUE TITLE
[Question] Composing multiple images

### ISSUE THREAD

**Issue by jakenuts** [imazen/imageflow-dotnet#27]
Is overlaying multiple images possible, and if so what would be the recommended way of achieving that? I gave multiple watermark calls a try and it did overlay them but the intermediate overlay lost it's transparency. I know this is a bit far afield for the library so "not today buddy" is a good answer.

Thanks!

**Comment by lilith** [comment]
Multiple overlays should work fine - perhaps we need more integration
tests. Can you share your code/json and source images?

**Comment by jakenuts** [comment]
[Here is an app](https://github.com/jakenuts/SharedCode/tree/main/ComposeImages) that demonstrates what I was seeing. It loads a "canvas" and then overlays three transparent color-grid pngs and saves the result to another png file. If the canvas is jpg, the watermarks all retain their transparency. If the canvas is a png, the first watermark is drawn without transparency. After running you can see the different outputs in the images folder.

https://github.com/jakenuts/SharedCode/tree/main/ComposeImages

![overlaid-on-jpg](https://user-images.githubusercontent.com/344606/111526378-e6254100-871b-11eb-8f19-88a517d60174.png)
![overlaid-on-png](https://user-images.githubusercontent.com/344606/111526380-e6bdd780-871b-11eb-96ab-a29aaa81aed8.png)


Thanks!

James

**Comment by lilith** [comment]
This has been fixed in 0.7.22. You can switch to the Imageflow.AllPlatforms package or replace your Imageflow.NativeRuntime.* dependencies.

**Comment by jakenuts** [comment]
Will do! Thanks so much!
