### ISSUE TITLE
docs?

### ISSUE THREAD

**Issue by rontoa20** [imazen/imageflow-dotnet#31]
wheres is the docs the links are broken :(

**Comment by tiesont** [comment]
Well, the project home page has some fairly extensive examples: https://github.com/imazen/imageflow-dotnet

The test suite also demonstrates most (if not all) of the API: https://github.com/imazen/imageflow-dotnet/blob/main/tests/Imageflow.Test/TestApi.cs

**Comment by lilith** [comment]
We're migrating and reworking our docs right now. Sorry for the
inconvenience!

**Comment by jawand** [comment]
thanks for this lib. 😊

Is there any update on the docs? Because I see no XML comments in the library as well. It would really be helpful if we get the documentation around this.

**Comment by lilith** [comment]
https://docs.imageflow.io is back online.
