### ISSUE TITLE
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll

### ISSUE THREAD

**Issue by paulflo150** [imazen/imageflow-dotnet#33]
Hi,
I am using .net 5 and I see several of these exceptions when calling imageflow for the very first time only:

`
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll ("Cannot implicitly convert type 'Newtonsoft.Json.Linq.JValue' to 'string'. An explicit conversion exists (are you missing a cast?)") Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll ("Cannot implicitly convert type 'Newtonsoft.Json.Linq.JValue' to 'string'. An explicit conversion exists (are you missing a cast?)")

Exception caught: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll ("'Newtonsoft.Json.Linq.JObject' does not contain a definition for 'name'") Exception caught: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll ("'Newtonsoft.Json.Linq.JObject' does not contain a definition for 'name'")
`

Has anyone else come across this problem?

As a side note, are there any plans on removing the dependency to Newtonsoft?

Thanks!

**Comment by lilith** [comment]
What version of Newtonsoft.Json are you using?

**Comment by paulflo150** [comment]
@lilith I have migrated all of my applications to System.Text.Json, but it looks like Imageflow pulled Newtonsoft version 12.0.1.22727.

**Comment by lilith** [comment]
I think this is now resolved (we needed Microsoft.CSharp to be present in later Newtonsoft versions). I'm open to moving to System.Text.Json if it can do the same dynamic object stuff - I haven't dug into it recently.
