### ISSUE TITLE
Constrain gravity

### ISSUE THREAD

**Issue by FlipSs** [imazen/imageflow-dotnet#34]
Hello, how can I specify gravity when using `Constrain` method?

![image](https://user-images.githubusercontent.com/25420767/121163427-707ecc00-c857-11eb-9c36-b5f8f00d4964.png)

**Comment by FlipSs** [comment]
I created a pull request for this #35

**Comment by lilith** [comment]
Thanks! Sorry we missed this, it will go into the next release

**Comment by lilith** [comment]
Sorry for the slow release, but it's on nuget now!
