### ISSUE TITLE
After conversion from JPEG to WebP image increased in size

### ISSUE THREAD

**Issue by NiJeTi** [imazen/imageflow-dotnet#38]
Using library to reduce incoming images size.

Used code:
```cs
public async Task<MemoryStream> ConvertStreamAsync(Stream input, CancellationToken cancellationToken)
{
    Log.Debug("Converting image stream");

    using var imagesProcessor = new ImageJob();
    var output = new MemoryStream();

    await imagesProcessor
       .Decode(input, false)
       .EncodeToStream(output, false, new WebPLosslessEncoder())
       .Finish()
       .WithCancellationToken(cancellationToken)
       .InProcessAsync();

    output.Position = 0;

    Log.Debug("Done converting image stream");

    return output;
}
```

`input` stream can contain JPEG, PNG, WebP and GIF

After passing 1.1 MB JPEG to input I received 4,82 MB WebP
![image](https://user-images.githubusercontent.com/5685857/127752686-8bab1d0b-c107-43a3-b4ee-6dffbad07471.png)

**Comment by lilith** [comment]
Lossless formats take up much more space than lossy formats. You might try
the lossy webp encoder and set an equivalent quality value to what the jpeg
was created with.

**Comment by NiJeTi** [comment]
Thanks for the explanation
