### ISSUE TITLE
ImageResizer to ImageFlow

### ISSUE THREAD

**Issue by nacoleman** [imazen/imageflow-dotnet#4]
Hi,

we have used ImageResizer for years now and we love it. We are looking to rebuild our application into .Net Core and so have been looking at ImageFlow.

I have seen a few examples of ImageFlow Middleware using imageflow-dotnet and have got this working to a point where it resizes the image etc.

My question might be due to purely not understanding the product but i wondered whether the configurations/extensions that were available for ImageResizer are in imageFlow. For example imageResizer>DiskCache.... should I set about writing the caching etc in my middleware or is this taken care of somewhere..

Apologies if i have missed documentation somewhere.

**Comment by nathanaeljones** [comment]
Middleware doesn't exist yet - the plan is to upgrade ImageResizer to use Imageflow.Net once Imageflow.Net has matured a bit more, at which point it will work that way. 

For now you would need to write your own, or copy/paste from ImageResizer's source code (the commercial licenses permit that).

**Comment by nacoleman** [comment]
ok thanks for the info and quick reply.
