### ISSUE TITLE
ImageFlow.AllPlatforms nuget package v 0.9.1 & 0.9.5 triggers Avast File Shield

### ISSUE THREAD

**Issue by eakova** [imazen/imageflow-dotnet#45]
Hi,
ImageFlow.AllPlatforms nuget package (version 0.9.1 & 0.9.5 ) triggers Avast File Shield as seen on screenshot below.
It could be a false-positive situation but anyway, It worths to check.
<img width="632" alt="Screen Shot 2023-03-14 at 15 58 48" src="https://user-images.githubusercontent.com/1556416/225038321-6a37eba7-2155-4324-859e-7e9045281eb3.png">

Regars,

**Comment by lilith** [comment]
I've submitted a false positive report to Avast. It appears the software has a really bad reputation for lazy file analysis and false positives, consider switching to a better service? I do appreciate the report, though, as it's possible others have encountered this.
