### ISSUE TITLE
Changing format and providing maxHeight/maxWidth without height/width changes image size

### ISSUE THREAD

**Issue by aheintz** [imazen/imageflow-dotnet#48]
We're using ImageFlow with command-string, and the query string `maxHeight=3200&maxWidth=3200&scale=both&format=png&up.filter=cubic&down.filter=cubic&f.sharpen=1` scales the image to fit within 3200x3200. 

If I remove `maxHeight` and `maxWidth` _or_ `scale=both` the original image size is retained.

If I don't provide a `height` or `width`, I think the expected result should be an image that maintains the size of the original. 

Tested on 0.10.0.

**Comment by lilith** [comment]
I assume the original image is less than 3200x3200?

Maxwidth/maxheight are more or less deprecated, and equivalent to
w=3200&h=3200&mode=max

Scale=both causes upscaling; scale=down is the default. Mode=max keeps
aspect ratio and fits to the bounds, mode=crop crops to the aspect ratio.

When you combine scale=both and mode=max, images will be upscaled to reach
the lesser of the two bounds while maintaining aspect ratio.
