### ISSUE TITLE
Microsoft.IO.RecyclableMemoryStream version conflict

### ISSUE THREAD

**Issue by MichaelSamteladze** [imazen/imageflow-dotnet#55]
We have a project where **Imageflow.AllPlatforms** and **EPPlus** packages are installed. When building a project we are getting a warning message
Warning	NU1608	Detected package version outside of dependency constraint: Imageflow.Net 0.10.2 requires Microsoft.IO.RecyclableMemoryStream (>= 1.2.2 && < 3.0.0) but version Microsoft.IO.RecyclableMemoryStream 3.0.0 was resolved.	

Can this be resolved?

**Comment by lilith** [comment]
This should be fixed in v0.11, I now test against version 1 and 3 both
