### ISSUE TITLE
How to crop image

### ISSUE THREAD

**Issue by andyfurniss4** [imazen/imageflow-dotnet#6]
Firstly, is this project still active? I can see there's been no commits or activity for a few months now but the packages are still pre-release so I'm assuming it's not complete yet.

I'd also like to ask if there is any documentation for imageflow yet? I'm trying to figure out how to crop an image but I'm struggling without any documentation or anything.

**Comment by nathanaeljones** [comment]
It is still active. The primary issue with Imageflow is that not enough people are using it for it to exit release candidate stage. 

These bindings don't add any processing features not present in Imageflow or ImageResizer 4. You can use either's API.
